version: "3.8"
services:
  mariadb:
    build: ./requirments/mariadb
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    env_file:
      ./.env
volumes:
  db:
