version: "3"

volumes:
  data: {}
  db: {}
services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB: ${WORDPRESS_DB}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/mysql/${WORDPRESS_DB}
    expose:
      - "3306"
    networks:
      - intra
    tty: true
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - intra
    tty: true
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB: ${WORDPRESS_DB}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    restart: always
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    tty: true
networks:
  intra:
    driver: bridge
