version: "3"

volumes:
  data: {}
  db: {}
services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DB=${MYSQL_DB}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - intra
    tty: true
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - intra
    tty: true
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    tty: true
networks:
  intra:
    driver: bridge
